nuc:
  id: nuc
  name: Ubuntu NUC
  category: server
  hostname: nuc-ubuntu
  operating_system: Ubuntu 24.04
  monitor: prometheus
  enabled: true
  linux:
    description: Primary Docker and Storage Server
    prometheus_job: nuc
    container_job: docker
    filesystems:
      - name: Ubuntu Root
        mountpoint: /
      - name: Media
        mountpoint: /media/tusa/Media
      - name: Storage
        mountpoint: /media/tusa/Storage
      - name: Data
        mountpoint: /media/tusa/Data

optiplex:
  id: optiplex
  name: Homeland OptiPlex
  category: server
  hostname: homeland
  operating_system: Ubuntu
  monitor: prometheus
  enabled: true
  linux:
    description: Primary Homeland Application Server
    prometheus_job: homeland-optiplex
    container_job:
    filesystems:
      - name: Ubuntu Root
        mountpoint: /

main-desktop:
  id: main-desktop
  name: Main Desktop
  category: workstation
  hostname: main-desktop
  operating_system: Windows 11
  monitor: prometheus
  enabled: true

windows-workstation:
  id: windows-workstation
  name: Windows Workstation
  category: workstation
  hostname: windows-workstation
  operating_system: Windows 11
  monitor: prometheus
  enabled: true

synology:
  id: synology
  name: Synology DS925+
  category: nas
  hostname: synology
  operating_system: DSM
  monitor: synology-api
  enabled: true

asustor:
  id: asustor
  name: Asustor NAS
  category: nas
  hostname: asustor
  operating_system: ADM
  monitor: none
  enabled: true

surface:
  id: surface
  name: Surface
  category: client
  hostname: greysurface
  operating_system: Windows
  monitor: none
  enabled: true

lenovo-tablet:
  id: lenovo-tablet
  name: Lenovo Tablet
  category: client
  hostname: lenovo-tablet
  operating_system: Android
  monitor: none
  enabled: true
