services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      HOMEPAGE_ALLOWED_HOSTS: "192.168.5.134:3000,nuc-ubuntu:3000"

    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/tusa/Data:/host-data:ro
      - /media/tusa/Media:/host-media:ro
      - /media/tusa/Storage:/host-storage:ro
      - /sys:/sys:ro

    restart: unless-stopped
